-- NT2 Woordenschat — yeni Supabase projesi için tablolar
-- (Zaten kurduysan tekrar çalıştırmana gerek yok.)
-- Supabase → SQL Editor → bu dosyanın tamamını yapıştır → Run

create table if not exists public.cards (
  id         bigint generated by default as identity primary key,
  date       text,
  type       text,
  dutch      text not null,
  turkish    text,
  uitleg     text,
  etymology  text,
  note       text,
  examples   jsonb default '[]'::jsonb,
  legal      text,
  is_legal   boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.progress (
  card_id      bigint primary key references public.cards(id) on delete cascade,
  is_known     boolean default false,
  sr_step      integer default 0,
  sr_next_due  text,
  sr_last_done text,
  updated_at   timestamptz default now()
);

create table if not exists public.app_state (
  key        text primary key,
  value      jsonb,
  updated_at timestamptz default now()
);

alter table public.cards     enable row level security;
alter table public.progress  enable row level security;
alter table public.app_state enable row level security;

drop policy if exists "nt2 all" on public.cards;
drop policy if exists "nt2 all" on public.progress;
drop policy if exists "nt2 all" on public.app_state;
create policy "nt2 all" on public.cards     for all to anon using (true) with check (true);
create policy "nt2 all" on public.progress  for all to anon using (true) with check (true);
create policy "nt2 all" on public.app_state for all to anon using (true) with check (true);
